Traceback (most recent call last):
  File "tracebackLogging.py", line 8, in <module>
    raise Exception("This is the error message.")
Exception: This is the error message.
